#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

# Exit immediately if a command exits with a non-zero status
set -e

echo "==> Setting application back to initial state..."

# Node
rm -rf \
    node_modules/ \

# React
rm -rf \
    dist/ \

# Jest
rm -rf \
    coverage/ \
    
echo "==> Setup complete."
