#!/bin/bash

# script/test: Run test suite for application.

# Exit immediately if a command exits with a non-zero status
set -e

# Store a local variable of the scripts current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${DIR}/bootstrap

echo "==> Running tests..."

yarn affected:lint
yarn affected:build
yarn affected:test
yarn affected:e2e --headless

echo "==> Tests complete."
